name: Build Python

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt
